#ifndef PDA_CONSTS_h
#define PDA_CONSTS_h

#define PDA_NUMBER_DISPLAYS 1

#define PDA_PIN_BUTTON_ENTER
#define PDA_PIN_BUTTON_BACK
#define PDA_PIN_BUTTON_CHANGE_SCREEN
#define PDA_PIN_BUTTON_UP
#define PDA_PIN_BUTTON_DOWN
#define PDA_PIN_BUTTON_LEFT
#define PDA_PIN_BUTTON_RIGHT

#define PDA_SPLASH_ID_BRAZIL    0
#define PDA_SPLASH_ID_ROCKETS   1


#define PDA_DISPLAY_HEIGHT      64
#define PDA_DISPLAY_WIDTH       128

#endif